### ISSUE TITLE
Provider version caching

### ISSUE THREAD

**Issue by leventyalcin** [opsgang/docker_aws_terraform#5]
Hey, 

Here just for the heads up. AFAIR, @aries1980 was asking for provider caching. 

@aries1980 check this out and raise your PR :) https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0107-october-2-2017

**Comment by jinal--shah** [comment]
Thanks @leventyalcin -

I can see the value of sharing a mounted volume for all terraform runs for CI/CD simplicity and performance.

*However we don't really need to change anything for that to work.*

Just run docker with `-e TF_PLUGIN_CACHE_DIR=/my/mounted/cache -v /my/host/dir:/my/mounted/cache`.

Alternatively, the user can create a .terraformrc with a derived image of their own.

Its easy enough to do this in a Dockerfile `FROM opsgang/aws_terraform:stable`

Then the user can choose what else to put in their .terraformrc (and which user's home dir that'll live in),
or even mount it from the container host.
